### ISSUE TITLE
Clicking on thc_w0018 shows a 404 error

### ISSUE THREAD

**Issue by MichaelSinz** [core-hacked/tesla-alerts-dictionary#10]
See image - this is from the web site https://tesla-alerts-dictionary.corehacked.com/

![image](https://github.com/user-attachments/assets/a3f69b17-5823-47a4-ae42-7d0095f3926a)

**Comment by MichaelSinz** [comment]
Note I think you wanted to use "thc_d0018" and not "thc_w0018" as opening https://tesla-alerts-dictionary.corehacked.com/alerts/thc_d0018.html works.

**Comment by core-hacked** [comment]
Thank you! Placed it with the other thc_dXXX errors and corrected it in the latest push, should work now. Really need to streamline this into JSON or MD and move to svelte, it's getting hard to maintain...
